#!/usr/bin/env ansible-playbook

- name: "Copia arquivo de configuração do MES e restarta o serviço - ELYTE"
  hosts:
    - raspelyte
  gather_facts: false
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: assets/mes-elyte.yml
        dest: /app/mes.yml
        owner: mes
        group: mes
        mode: "0644"
    - name: Start mesdaemon service
      ansible.builtin.systemd:
        state: restarted
        name: mesdaemon.service

- name: "Copia arquivo de configuração do MES e restarta o serviço - FUNDIMISA"
  hosts:
    - raspfundimisa
  gather_facts: false
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: assets/mes-fundimisa.yml
        dest: /app/mes.yml
        owner: mes
        group: mes
        mode: "0644"
    - name: Start mesdaemon service
      ansible.builtin.systemd:
        state: restarted
        name: mesdaemon.service
